### ISSUE TITLE
how to access shared preferences data in Java?

### ISSUE THREAD

**Issue by jynlix** [sriraman/react-native-shared-preferences#12]
I guess we need use "wit_player_shared_preferences" to get the shared preferences?
Please give an example in readme.
thanks

**Comment by jerroldlaw** [comment]
Yes, it seems like in SharedHandler.java, the shared preference name is declared as a final string.

private static final String SHARED_NAME = "wit_player_shared_preferences";

To answer your question, to access shared preferences natively you should use something along the lines of:

SharedPreferences prefs = getSharedPreferences("wit_player_shared_preferences", Context.MODE_PRIVATE);
String example = prefs.getString(KEY, "");

Now for my question,

What is "wit_player_shared_preferences"?

**Comment by sriraman** [comment]
actually, My Bad.

I have named it like `wit_player_shared_preferences` when I was making it for my personal project. I forgot to change it when I was open sourcing it. I'll update it with better naming convention when I'm releasing 2.X

**Comment by rochapablo** [comment]
Can you give us an example of how get shared preferences in Java?
