### ISSUE TITLE
Please, make SHARED_NAME configurable

### ISSUE THREAD

**Issue by michaelkruglos** [sriraman/react-native-shared-preferences#16]
Please, make SHARED_NAME configurable
https://github.com/sriraman/react-native-shared-preferences/blob/3bb0f1e7a4e592a9885bcbaf27f718665d81ec8e/android/src/main/java/in/sriraman/sharedpreferences/SharedHandler.java#L10

I think there's outstanding pull request for it.

**Comment by sriraman** [comment]
#13 

Merged the above PR. Now you will be able to configure it.
