### ISSUE TITLE
error in iOS when using setItem

### ISSUE THREAD

**Issue by rohitpaniker** [sriraman/react-native-shared-preferences#24]
Error:
[TypeError: null is not an object (evaluating '_reactNativeSharedPreferences.default.setItem')]

What is causing:

SharedPreferences.setItem("loginState", 'true');
SharedPreferences.setItem("userDetails", JSON.stringify(signUpResult.data));

Affected Platform: iOS

on Android is working fine.

Please help me resolve this issue.

**Comment by sriraman** [comment]
We are not supporting iOS system as of now..

As of now, You can add condition (Platform.OS === 'iOS') and use AsyncStorage for iOS in that case.

If you don't want to access the shared preference from native layer.. Using AsyncStorage will be good for your requirement.

**Comment by rohitpaniker** [comment]
Thanks Sriraman, I will work on our suggestions.




Rohit Paniker


m: +91-9819765981
w: www.about.me/rohitpaniker  e: rohit.paniker.1990@gmail.com
<rohitatlap@gmail.com>
