### ISSUE TITLE
how getitem and pass to variable?

### ISSUE THREAD

**Issue by deividnn** [sriraman/react-native-shared-preferences#25]
SharedPreferences.getItem("logvenda", function (value) {
        console.log(value);
        this.setState({logvenda:value});
      });
      console.log(this.state.logvenda);
 
error:
TypeError: undefined is not an
object (evaluating 'this.setState')

**Comment by mhmmdzde** [comment]
I've same error!!!
error:
TypeError: undefined is not an
object (evaluating 'this.setState')

**Comment by sriraman** [comment]
Sorry for the delayed reply.. Actually, `this` might not have binded to the function..

Try this....
```
SharedPreferences.getItem("logvenda", (value) => {
    console.log(value);
    this.setState({logvenda:value});
});
```
