### ISSUE TITLE
Get All Keys Support

### ISSUE THREAD

**Issue by sirnacnud** [sriraman/react-native-shared-preferences#3]
I noticed there appears to be some support to get all the keys from SharedPreferences, but it is commented out.  Was there a particular problem you ran in to implementing it?

**Comment by sriraman** [comment]
Yes. I was trying to return as a string. It didn't work properly. Then only, I get to know that I can return Array by using [ReadableArray](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableArray.java). Then, I didn't get time to implement it. I will try to add it by this weekend.

**Comment by sriraman** [comment]
Implemented in v0.0.6 37846e30e47cd3f7c9332c7dc79db7ea1cf0a9ae

You can use `getAll()` to get all the keys stored in the shared preferences
