### ISSUE TITLE
Access preferences from the native realm

### ISSUE THREAD

**Issue by Exilz** [sriraman/react-native-shared-preferences#6]
Hi, thanks for the plugin.

I'd like to know if it's possible to access stored preferences from java code ? From MainApplication or a custom module for instance.

I'm struggling to share persistent data between javascript and native sides.

Thanks :)

**Comment by sriraman** [comment]
Yes. You can directly access these data from native JAVA. I'm using [Android's Native SharedPreferences](https://developer.android.com/reference/android/content/SharedPreferences.html) only. Sharing persistent data between javascript and Java was the main motivation to create this module.

**Comment by Exilz** [comment]
Fantastic, I didn't even know about this api. Thanks for the quick answer.

**Comment by jynlix** [comment]
is there any examples for this issue?  thanks
