### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.String in.sriraman.sharedprefrences.SharedHandler.getString(java.lang.String)' on a null object references

### ISSUE THREAD

**Issue by yoginair-dev** [sriraman/react-native-shared-preferences#7]
Here when I retrieving the value after some time like 1 day ago ...i get this error ....is there any storing logic is time specific...

**Comment by sujithkanna** [comment]
Can you share the code?

**Comment by yoginair-dev** [comment]
SharedPreferences.setItem("user_id ", user_id );

 SharedPreferences.getItem("sender_id", (value) => {
 user_id = value;
//here I use fetch function and some time i get this error
});

**Comment by sujithkanna** [comment]
Code looks fine. Do you have the full stacktrace of the error???

**Comment by yoginair-dev** [comment]
Now its working fine...i think the issue is raised because of i am setting the null value to the key ...
